# Generated by Django 5.2.9 on 2026-01-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNTRY', models.CharField(db_index=True, max_length=100)),
                ('INDICATOR', models.CharField(db_index=True, max_length=200)),
                ('FREQUENCY', models.CharField(max_length=50)),
                ('SCALE', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['COUNTRY', 'INDICATOR'],
                'indexes': [models.Index(fields=['COUNTRY', 'INDICATOR'], name='idx_country_indicator')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_country', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_indicator', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('old_rate', models.FloatField(blank=True, null=True)),
                ('new_rate', models.FloatField()),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['currency_country', 'updated_at'], name='idx_audit_currency_date')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('rate', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency_app.currency')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['currency', 'year', 'month'], name='idx_currency_date'), models.Index(fields=['rate'], name='idx_rate')],
                'unique_together': {('currency', 'year', 'month')},
            },
        ),
    ]
