# Generated by Django 5.2.9 on 2026-01-20 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_alter_currency_options_remove_currency_m01_2000_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('old_rate', models.FloatField(blank=True, null=True)),
                ('new_rate', models.FloatField()),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['COUNTRY', 'INDICATOR']},
        ),
        migrations.AlterModelOptions(
            name='monthlyrate',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='COUNTRY',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='INDICATOR',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['COUNTRY', 'INDICATOR'], name='idx_country_indicator'),
        ),
        migrations.AddIndex(
            model_name='monthlyrate',
            index=models.Index(fields=['currency', 'year', 'month'], name='idx_currency_date'),
        ),
        migrations.AddIndex(
            model_name='monthlyrate',
            index=models.Index(fields=['rate'], name='idx_rate'),
        ),
        migrations.AddField(
            model_name='currencyrateaudit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='currency_app.currency'),
        ),
        migrations.AddIndex(
            model_name='currencyrateaudit',
            index=models.Index(fields=['currency', 'updated_at'], name='idx_audit_currency_date'),
        ),
    ]
